### ISSUE TITLE
[Bug] ...  don't block camera 

### ISSUE THREAD

**Issue by sabamdarif** [stuarthayhurst/privacy-menu-extension#38]
**Describe the issue**
 if i disable camera access  from quick setting , it don't block the camera for any app , they still use the camera 

**To Reproduce**
1. Go to 'new camera application of gnome'
4. See the error

**Expected behavior**
A clear and concise description of what you expected to happen

**Screenshots and logs**
If applicable, add screenshots and logs to help explain your problem
Help on obtaining a log can be found [here](https://github.com/stuarthayhurst/privacy-menu-extension#bug-reporting--debugging)

**System information (please complete the following information):**
 - Distro: [Fedora]
 - GNOME version: (45.1)
 - Extension version (21)

**Additional context**
Add any other context about the problem here

**Comment by stuarthayhurst** [comment]
From the README:
 - Due to limitations in GNOME shell, only sandboxed (flatpak / snap) apps can be forced to respect privacy settings
 - As long as the settings changed by the extension match the settings inside GNOME Settings (privacy section), the extension is behaving correctly

Can you verify that the settings are being changed inside GNOME Settings? If they are, then this is another case of the application not respecting the privacy settings.
